const productos = [{
        id: 1,
        nombre: "REMERA KITTY KITTY",
        imagen: "img/remerablanca.webp",
        precio: 21990,
    },
    {
        id: 2,
        nombre: "REMERA $INNER",
        imagen: "img/remeranegra.webp",
        precio: 19600,
    },
    {
        id: 3,
        nombre: "REMERA ROOT",
        imagen: "img/remera4.png",
        precio: 19600,
    },
    {
        id: 4,
        nombre: "REMERA WASHED",
        imagen: "img/remerawashed.webp",
        precio: 21900,
    },
    {
        id: 5,
        nombre: "HOODIE BSTRD RENEWED",
        imagen: "img/buzoblanco.webp",
        precio: 36900,
    },
    {
        id: 6,
        nombre: "HOODIE LOGO 3",
        imagen: "img/buzonegro.webp",
        precio: 36900,
    },
    {
        id: 7,
        nombre: "HOODIE 13",
        imagen: "img/buzorosa.webp",
        precio: 34900,
    },
    {
        id: 8,
        nombre: "B$T CARGO",
        imagen: "img/cargo.webp",
        precio: 18500,
    },
    {
        id: 9,
        nombre: "SAD BA$TARD",
        imagen: "img/remerasadbastard.webp",
        precio: 21900,
    },
    {
        id: 10,
        nombre: "HOODIE BADDIE",
        imagen: "img/buzobaddie.webp",
        precio: 34900,
    },
    {
        id: 11,
        nombre: "HOODIE MAGAZINE",
        imagen: "img/buzomagazine.webp",
        precio: 34900,
    },
    {
        id: 12,
        nombre: "VOID",
        imagen: "img/remeravoid.webp",
        precio: 21990,
    },
    {
        id: 13,
        nombre: "WELL DONE",
        imagen: "img/remerawelldone.webp",
        precio: 19600,
    },
    {
        id: 14,
        nombre: "HOODIE KILLINGME SOFTLY",
        imagen: "img/buzokillingmesoftly.webp",
        precio: 36900,
    },
    {
        id: 15,
        nombre: "SOCK BA$TARD",
        imagen: "img/sockbastard.webp",
        precio: 2990,
    },
    {
        id: 16,
        nombre: "SOCK DEMON",
        imagen: "img/sockdemon.webp",
        precio: 2990,
    },
    {
        id: 17,
        nombre: "LLAVERO DEMON",
        imagen: "img/llaveros.webp",
        precio: 1300,
    },
    {
        id: 18,
        nombre: "HOODIE NEW $TANDARD",
        imagen: "img/rinobastard.webp",
        precio: 36900,
    },
    {
        id: 19,
        nombre: "MINI BAG BA$TARD",
        imagen: "img/buzonewstandar.webp",
        precio: 22900,
    },
    {
        id: 20,
        nombre: "LOVE $TORY",
        imagen: "img/lovestrory.webp",
        precio: 19600,
    },
];